### ISSUE TITLE
`"Appboy-iOS-SDK/AppboyKit.h" file not found` with cocoapods 1.0.0.beta.6

### ISSUE THREAD

**Issue by ldiqual** [Appboy/appboy-segment-ios#4] opened 2016-03-24 18:12 UTC
Hey there!

I get the following error when building with cocoapods 1.0.0.beta.6 dependencies:

```
"Appboy-iOS-SDK/AppboyKit.h" file not found
```

which refers to this line: https://github.com/Appboy/appboy-segment-ios/blob/master/Pod/Classes/SEGAppboyIntegration.m#L2

My pod version is 1.0.0 (not the latest), but those lines are unchanged in the last version so I believe it doesn't matter here.

Temporary fix (notice the underscores):

```
-#import "Appboy-iOS-SDK/AppboyKit.h"
-#import "Appboy-iOS-SDK/ABKUser.h"
+#import <Appboy_iOS_SDK/AppboyKit.h>
+#import <Appboy_iOS_SDK/ABKUser.h>
```

Example in a Podfile:

```
post_install do |installer|
    # Workaround https://github.com/Appboy/appboy-segment-ios/issues/4
    path = "./Pods/Segment-Appboy/Pod/Classes/SEGAppboyIntegration.m"
    File.chmod(0644, path)
    File.write(path, File.open(path, &:read)
        .gsub('#import "Appboy-iOS-SDK/AppboyKit.h"', "#import <Appboy_iOS_SDK/AppboyKit.h>")
        .gsub('#import "Appboy-iOS-SDK/ABKUser.h"', "#import <Appboy_iOS_SDK/ABKUser.h>")
    )
end
```

**Comment by ldiqual** [comment] 2016-04-12 23:54
Bump cc @briancaw

**Comment by briancaw** [comment] 2016-04-12 23:58
Hey @ldiqual 

Apologies for the delay here this one slipped by our reporting somehow.  We'll be investigating shortly and will respond with our findings ASAP.

Thanks,
Brian

**Comment by Wenzhi** [comment] 2016-04-21 18:27
Hi @ldiqual,

Thanks for reaching out for the issue and providing a solution! I think the issue is caused by how Cocoapods generates frameworks: when using `use_frameworks!` in Podfile, all `Appboy-iOS-SDK` become `Appboy_iOS_SDK`.

I will ask Cocoapods team about the issue, also how we should handle it as an SDK. For now, I think your solution with Podfile change would be good.

Thanks again!
Wenzhi

**Comment by BenjaminPrieur** [comment] 2016-07-11 10:24
Hi guys,

This issue could be fixed with this piece of code (You are using it in Segment-Amplitude)
```
#if defined(__has_include) && __has_include(<Amplitude_iOS/Amplitude.h>)
#import <Appboy_iOS_SDK/AppboyKit.h>
#import <Appboy_iOS_SDK/ABKUser.h>
#else
import "Appboy-iOS-SDK/AppboyKit.h"
#import "Appboy-iOS-SDK/ABKUser.h"
#endif
```

I will really appreciate if you could integrate it in your next release ;)
Thanks
Ben

**Comment by Wenzhi** [comment] 2016-08-01 20:01
Hey All,

We updated the SDK with the change that fixes this issue. Please check the latest version - 1.0.4 - and feel free to reopen if you're still seeing the issue.

Special thanks for the code, @BenjaminPrieur!

Thanks,
Wenzhi

**Comment by chshapiro** [comment] 2016-09-19 20:40
Hey @anand00,

Can you let us know what version of Segment-Appboy you are using? And can you let us know what version of Cocoapods you are using?

We're actively debugging against current versions; thanks for reporting!

Thanks,
Chava

**Comment by briancaw** [comment] 2016-12-30 17:32
Hi @anand00 

Any update here - are you still having this issue?  Going to close this out for now, but please let us know if you still have this issue.

Thanks,
Brian

**Closed by briancaw** 2016-12-30 17:32 UTC
